import numpy as np
import os
import yaml

import matplotlib.pyplot as plt

class MillardMuscle:
    def __init__(self, name, config):
        m_cfg = config['muscles'][name]
        d_cfg = config.get('dynamics_params', {})
        c_cfg = config.get('muscle_curves', {}) 
        
        self.f_iso_max = m_cfg['f_iso_max']
        self.l_ce_opt = m_cfg['l_ce_opt']
        self.l_slack = m_cfg['l_slack']
        self.alpha_opt = m_cfg['pennation_angle']
        self.v_max = m_cfg['v_max']
        self.moment_arm = m_cfg['moment_arm']
        self.tau_act = m_cfg['tau_act']
        self.tau_dact = m_cfg['tau_dact']
        
        self.fv_k = d_cfg.get('fv_k', c_cfg.get('concentric_slope_near_vmax', 0.25))
        self.fv_ecc_max = d_cfg.get('fv_ecc_max', c_cfg.get('eccentric_max_force', 1.4))
        self.beta = d_cfg.get('muscle_damping_beta', 0.1)

    def get_activation_derivative(self, u, a):
        """Calculates da/dt based on excitation u and current activation a."""
        tau = self.tau_act if u >= a else self.tau_dact
        return (u - a) / tau

    def get_force(self, theta, omega, a):
        l_mtu = self.l_slack + self.l_ce_opt - (self.moment_arm * theta)
        l_norm = (l_mtu - self.l_slack) / self.l_ce_opt
        v_norm = (-self.moment_arm * omega) / (self.v_max * self.l_ce_opt)

        # Active: Gaussian-like curve
        f_al = np.exp(-((l_norm - 1)**2) / 0.45) 
        
        # Passive: Exponential (Slack beyond 1.0)
        f_pe = (np.exp(5.0 * (l_norm - 1.0)) - 1.0) / (np.exp(5.0) - 1.0) if l_norm > 1.0 else 0 
        
        # Force-Velocity: Derived from normalized curves and scaled by config parameters
        if v_norm <= 0: # Concentric (Shortening)
            f_v = (1 + v_norm) / (1 - v_norm / self.fv_k)
        else: # Eccentric (Lengthening)
            f_v = (self.fv_ecc_max + 0.8 * (1 + v_norm) / (1 + v_norm / self.fv_k)) / (1 + 0.8/self.fv_k)
        
        # Total Force with Improved Dynamics Damping Model Assuming Rigid Tendon
        f_tendon = self.f_iso_max * (a * f_al * f_v + f_pe + self.beta * v_norm) * np.cos(self.alpha_opt)
        return f_tendon

    def get_torque(self, theta, omega, a):
        """Returns the torque generated by this muscle at the joint."""
        return self.get_force(theta, omega, a) * self.moment_arm
    
if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
    config_path = os.path.join(project_root, "configs", "config.yaml")

  
    with open(config_path, 'r') as f:
        full_config = yaml.safe_load(f)
   

    ta = MillardMuscle('TA', full_config)
    sol = MillardMuscle('Soleus', full_config)

    angles_deg = np.linspace(-45, 20, 100)
    angles_rad = np.radians(angles_deg)

    ta_torques = [ta.get_torque(a, 0, 1.0) for a in angles_rad]
    sol_torques = [sol.get_torque(a, 0, 1.0) for a in angles_rad]

    plt.figure(figsize=(10, 5))
    plt.plot(angles_deg, ta_torques, 'b-', label='Tibialis Anterior (Dorsiflexor)', lw=2)
    plt.plot(angles_deg, sol_torques, 'r-', label='Soleus (Plantarflexor)', lw=2)
    plt.axhline(0, color='black', ls='--')
    plt.title("Muscle Torque Capability")
    plt.xlabel("Ankle Angle (degrees)")
    plt.ylabel("Torque (Nm)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()