import numpy as np
import os
import yaml

import matplotlib.pyplot as plt

class MillardMuscle:
    def __init__(self, name, config):
        m_cfg = config['muscles'][name]
        d_cfg = config['dynamics_params']
        c_cfg = config['muscle_curves']
        
        self.f_iso_max = m_cfg['f_iso_max']
        self.l_ce_opt = m_cfg['l_ce_opt']
        self.l_slack = m_cfg['l_slack']
        self.alpha_opt = m_cfg['pennation_angle']
        self.v_max = m_cfg['v_max']
        self.moment_arm = m_cfg['moment_arm']
        self.tau_act = m_cfg['tau_act']
        self.tau_dact = m_cfg['tau_dact']
        
        self.fv_k = d_cfg['fv_k']
        self.fv_ecc_max = d_cfg['fv_ecc_max']
        self.beta = d_cfg['muscle_damping_beta']
        
        self.width = c_cfg['width']
        self.gauss_tilt = c_cfg['gaussian_factor']
        self.passive_shape = c_cfg['passive_shape']
        self.passive_strain = c_cfg['passive_strain']
        
        self.k_pe = self.passive_shape / self.passive_strain

    def get_activation_derivative(self, u, a):
        """Calculates da/dt based on excitation u and current activation a."""
        tau = self.tau_act if u >= a else self.tau_dact
        return (u - a) / tau

    def get_force(self, theta, omega, a):
        l_mtu = self.l_slack + self.l_ce_opt - (self.moment_arm * theta)
        
        # simplification bsaed on optimal pennation angle and geometric considerations
        cos_alpha = np.sqrt(max(0.01, 1 - (self.l_ce_opt * np.sin(self.alpha_opt) / max(0.001, l_mtu - self.l_slack))**2))
        l_norm = ((l_mtu - self.l_slack) / cos_alpha) / self.l_ce_opt
        v_norm = (-self.moment_arm * omega * cos_alpha) / (self.v_max * self.l_ce_opt)
        
        # AL,PE for Force-Length Curves
        f_al = np.exp(-((l_norm - 1.0)**2) / (self.width + self.gauss_tilt * (l_norm - 1.0)))
        f_pe = (np.exp(self.k_pe * (l_norm - 1.0)) - 1.0) / (np.exp(self.passive_shape) - 1.0) if l_norm > 1.0 else 0 
        
        # Force-Velocity
        if v_norm <= 0: # Concentric (Shortening)
            f_v = (1 + v_norm) / (1 - v_norm / self.fv_k)
        else: # Eccentric (Lengthening)
            v_crit = (self.fv_ecc_max - 1) / (1 + 1/self.fv_k)
            f_v = (self.fv_ecc_max * v_norm + v_crit) / (v_norm + v_crit)
            
        f_tendon = self.f_iso_max * (a * f_al * f_v + f_pe + self.beta * v_norm) * cos_alpha
        return f_tendon

    def get_torque(self, theta, omega, a):
        """Returns the torque generated by this muscle at the joint."""
        return self.get_force(theta, omega, a) * self.moment_arm
    
if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
    config_path = os.path.join(project_root, "configs", "config.yaml")

  
    with open(config_path, 'r') as f:
        full_config = yaml.safe_load(f)
   

    ta = MillardMuscle('TA', full_config)
    sol = MillardMuscle('Soleus', full_config)

    angles_deg = np.linspace(-45, 20, 100)
    angles_rad = np.radians(angles_deg)

    ta_torques = [ta.get_torque(a, 0, 1.0) for a in angles_rad]
    sol_torques = [sol.get_torque(a, 0, 1.0) for a in angles_rad]

    plt.figure(figsize=(10, 5))
    plt.plot(angles_deg, ta_torques, 'b-', label='Tibialis Anterior (Dorsiflexor)', lw=2)
    plt.plot(angles_deg, sol_torques, 'r-', label='Soleus (Plantarflexor)', lw=2)
    plt.axhline(0, color='black', ls='--')
    plt.title("Muscle Torque Capability")
    plt.xlabel("Ankle Angle (degrees)")
    plt.ylabel("Torque (Nm)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()